Update plugin-manager.asciidoc
remove is notsupported. should be used `uninstall` instead of remove

```
bin/logstash-plugin remove logstash-output-kafka
ERROR: No such sub-command 'remove'

See: 'bin/logstash-plugin --help'
```