Mark "target" field as required in json filter
Without it in config file logstash is throwing following error for completely valid JSON file:
:exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :level=>:warn