The match option is required for the email output plugin
Whilst modifying the plugin to support sendmail delivery
the requirement for the match option was removed.

The change was made in this commit:

ef280184946ae974d6185db674e60d43dce4ea21

This causes the email plugin to fail with the following error:

undefined method `each' for nil:NilClass

Tracing back to:

/opt/logstash/logstash.jar!/logstash/outputs/email.rb:173:in `receive'"

This commit reverts that change and marks the match option as
required.