Backport PR #12784 (#12805) to 7.x: Fix: logstash-keystore failing with an error (#12803)
* Fix: logstash-keystore failing with an error (#12784)

* Fix: missing password dependency require

which causes `bin/logstash-keystore` to fail with an error:
```
ERROR: Failed to load settings file from "path.settings". Aborting...
path.setting=/logstash-7.12.0/config, exception=NameError,
message=>uninitialized constant LogStash::Util::Password

```

* Fix: review all LS parts depending on Password

* Test: bin/logstash-keystore create/list

(cherry picked from commit e8e393bdc763588e51dbc24b4d8b688a05de2351)

* Test: let's do the cleanup for every test