- restore -t/--configtest flag accidentally removed in the previous released (LOGSTASH-1279)
Testing -
  % bin/logstash agent -e '' --configtest
  Configuration OK

  % bin/logstash agent -e 'asdf' --configtest
  Error: Expected one of #, input, filter, output at line 1, column 1
  (byte 1) after