Use previous patch release for upgrade
Specifically for the 7.17 branch and only on RHEL/CentOS/OEL-7
(and earlier) it's not possible to upgrade from the latest release
(e.g. 7.17.16) to a newer snapshot build (7.17.16-SNAPSHOT) with
yum reporting `<package> does not update installed package.`[^1]

This commit uses the previous patch release for the upgrade test.

[^1]: Error: Nothing to do
    ```
    $ rpm -qi logstash
    Name        : logstash
    Epoch       : 1
    Version     : 7.17.16
    Release     : 1
    Architecture: x86_64
    Install Date: Wed 10 Jan 2024 12:58:12 PM UTC
    Group       : default
    Size        : 623783615
    License     : Elastic License
    Signature   : RSA/SHA512, Fri 08 Dec 2023 04:59:38 PM UTC, Key ID d27d666cd88e42b4
    Source RPM  : logstash-7.17.16-1.src.rpm
    Build Date  : Tue 05 Dec 2023 12:12:07 PM UTC
    Build Host  : bk-agent-prod-gcp-1701777732448852542.c.elastic-ci-prod.internal
    Relocations : /
    Packager    : <buildkite-agent@bk-agent-prod-gcp-1701777732448852542>
    Vendor      : Elastic
    URL         : https://www.elastic.co/logstash
    Summary     : An extensible logging pipeline
    Description :
    An extensible logging pipeline

    $ sudo yum install logstash/build/logstash-7.17.16-SNAPSHOT-x86_64.rpm
    Loaded plugins: copr
    Examining logstash/build/logstash-7.17.16-SNAPSHOT-x86_64.rpm: 1:logstash-7.17.16~SNAPSHOT-1.x86_64
    logstash/build/logstash-7.17.16-SNAPSHOT-x86_64.rpm: does not update installed package.
    Error: Nothing to do
    ```