multiple fixes for redis output, mostly related to batch mode. Fixes LOGSTASH-573
  - when logging exception, variable is pending_count not pending. (LOGSTASH-573)
  - using @password.value when connecting causes "undefined method `value' for nil:NilClass"
    if no password is in use.
  - re-raising a handled exception causes a fatal error. Nothing higher in the stack
    handles it. So logstash dies if redis is down. Alternately, I could wrap begin/rescue
    blocks around calls to process_pending if that's preferred style...
  - since exception isn't being re-raised, we don't need the extra @pending_mutex.unlock.
    Otherwise we get "ThreadError: Attempt to unlock a mutex which is not locked"