Add libc6-dev dependency to the deb package
This is required to resolve a Java 8 + JRuby FFI bug which causes
File::Stat#dev_minor and similar functions to raise this exception:

> NotImplementedError: block device detection unsupported or native
> support failed to load

References
* https://github.com/elastic/logstash/issues/3127
* https://github.com/jruby/jruby/issues/2913

Fixes #3216